# numpy numerical phython

In [2]:
%time import numpy as np #first import the module*

Wall time: 0 ns


In [ ]:
# 1 dimension = vector , 2 dimension = TENSOR (matrics)
#DATA HAVE SHAPE 

In [1]:
oneD =np.array([1,2,3,4,4])

NameError: name 'np' is not defined

In [2]:
oneD


NameError: name 'oneD' is not defined

In [3]:
type(oneD)

NameError: name 'oneD' is not defined

In [4]:
oneD.shape ###vector shape

NameError: name 'oneD' is not defined

In [5]:
zeeroD = np.array(900)

NameError: name 'np' is not defined

In [6]:
type(zeeroD)

NameError: name 'zeeroD' is not defined

In [7]:
zeeroD

NameError: name 'zeeroD' is not defined

In [8]:
twod = np.array([[[[[[100,67]]]]]])

NameError: name 'np' is not defined

In [9]:
twod.ndim


NameError: name 'twod' is not defined

In [10]:
twod.shape

NameError: name 'twod' is not defined

In [11]:
twood=np.arange(10).reshape(5,2)   ###five row two coulomb

NameError: name 'np' is not defined

In [12]:
twood


NameError: name 'twood' is not defined

In [13]:
twoood=np.arange(10)

NameError: name 'np' is not defined

In [14]:
twoood=np.arange(10).reshape(2,5) #######two row five coulomb

NameError: name 'np' is not defined

In [15]:
twoood

NameError: name 'twoood' is not defined

In [16]:
#if the number is prime than we use it as 1,13 0r 13,1

In [17]:
#(2,3,3) here two is depth

In [18]:
#revise 3d


In [19]:
#chage data type from "a".astype here a is variable

In [20]:
alist=[1,2,3,4,5,6,7,8,9]

In [21]:
blist=[]
for num in alist:
    blist.append(num*5)
blist

[5, 10, 15, 20, 25, 30, 35, 40, 45]

In [22]:
alist = np.arange(20).reshape(4,5)

NameError: name 'np' is not defined

In [ ]:
alist

In [ ]:

alist *2

In [ ]:
# PIAIC 2 CLASS WORK


In [23]:
arr= np.arange(1,37).reshape(6,6)

NameError: name 'np' is not defined

In [ ]:
arr

In [ ]:
#getting a single complete row 

In [24]:
#getting a single complete row 
arr[2:3,0:7]    # 1 way to get row 

NameError: name 'arr' is not defined

In [25]:
arr[2,:]# 2 way to get row

NameError: name 'arr' is not defined

In [26]:
arr[2]# 3 way to get row

NameError: name 'arr' is not defined

In [27]:
arr[:,4]#1 dimension

NameError: name 'arr' is not defined

In [12]:
arr[0:6,4:5] #two dimension because of use(define) of row and coulomb completely

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [13]:
arr[:,::2]  #right to left  2 is positive

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [14]:
arr[:,::-2] # left to right because -2 is negative

array([[ 6,  4,  2],
       [12, 10,  8],
       [18, 16, 14],
       [24, 22, 20],
       [30, 28, 26],
       [36, 34, 32]])

In [15]:
arr[:,::-3]

array([[ 6,  3],
       [12,  9],
       [18, 15],
       [24, 21],
       [30, 27],
       [36, 33]])

In [16]:
arr[::2,:]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18],
       [25, 26, 27, 28, 29, 30]])

In [17]:
arr[::-2,:]

array([[31, 32, 33, 34, 35, 36],
       [19, 20, 21, 22, 23, 24],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
#ones like take the shape and dimension of the matrics 

In [19]:
arr[::-2,::-2]

array([[36, 34, 32],
       [24, 22, 20],
       [12, 10,  8]])

In [20]:
d3 =  np.arange(50).reshape(2,5,5)

d3

In [21]:
d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [23]:
#indeximg  pick 17
d3.shape

(2, 5, 5)

In [24]:
d3[1,3,2]

42

In [25]:
d3[0,3,2]

17

In [26]:
d3[0][3][2]

17

In [27]:
d3[0][3][1:4]

array([16, 17, 18])

In [35]:
d3[1][:][1:2]

array([[30, 31, 32, 33, 34]])

In [36]:
d3[1,:,1:2] #coulomb

array([[26],
       [31],
       [36],
       [41],
       [46]])

In [40]:
d3[1][:][1:2]

array([[30, 31, 32, 33, 34]])

In [44]:
d3[1][:][1:2]

array([[30, 31, 32, 33, 34]])

# BOLEAN

In [3]:
DATA = np.arange(64).reshape(8,8)

In [4]:
DATA

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [5]:
DATA[DATA>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [16]:
bolarr=np.array([False,False,True,True,False,True,True,False],dtype ="bool")

In [9]:
DATA

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [17]:
bolarr

array([False, False,  True,  True, False,  True,  True, False])

In [10]:
DATA[3]

array([24, 25, 26, 27, 28, 29, 30, 31])

In [12]:
DATA[[2,1,6,4,0]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [24]:
bolarr = np.array(["ali","nehal","sameer","azhar","ali","sameer","azhar","ali"])
cond = bolarr =="ali"
cond

array([ True, False, False, False,  True, False, False,  True])

In [25]:
DATA[cond]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [26]:
cond = (bolarr =="ali") | (bolarr=="sameer")

In [27]:
cond

array([ True, False,  True, False,  True,  True, False,  True])

In [29]:
DATA[cond]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [56, 57, 58, 59, 60, 61, 62, 63]])

fancy and indexing

In [33]:
arr = np.ones((8,4))

In [34]:
arr=np.ones((8,4))

In [35]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
arr = np.ones((8,4),dtype ="int")

In [37]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
for i in range(8):
    arr[i]=i
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [43]:
arr[2]

array([2, 2, 2, 2])

In [44]:
arr[[7,3,2,0],1:3]

array([[7, 7],
       [3, 3],
       [2, 2],
       [0, 0]])

In [45]:
arr = np.arange(16).reshape(4,4)

In [46]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
#T transpose change row into coulomb

In [48]:
import matplolib.pyplot as plt

ModuleNotFoundError: No module named 'matplolib'

In [ ]:
# mean() or average